// <auto-generated />
namespace Pfizer.QueueSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class QueueHistoryAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QueueHistoryAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201802050702557_QueueHistoryAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
